device_id = "a3be6fc1-f605-4bf4-be4f-d79d8eb01102"
access_token = "567511eb-6a79-487d-8f93-ea9e2eea6554"
cert_pem = """
-----BEGIN CERTIFICATE-----
MIHrMIGToAMCAQICAQAwCgYIKoZIzj0EAwIwADAeFw0yNjA5MjYxNjQzMjFaFw0y
NzA5MjYxNjQzMjFaMAAwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASIrcsfoxKd
OXRo61loXOxxDsSM8+eBHHNh9NJEvQxk911CQcXi9FdQNocD2WtUJo28sEgp/6A/
bmeIPpdEBIoZMAoGCCqGSM49BAMCA0cAMEQCIDKqt5BQ0CRZ3Pxu7d+EwjniBvE8
R0fC1619oABsTfL5AiB5VMpBOpZE+fnLmdr6YXHN4l30I8pby1ql2pIxjmK/4g==
-----END CERTIFICATE-----
"""
key_pem = """
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgA3J87N8yQb0MOxwm
hmtGTPPiSR8kixVx9D4hLnQo5XOhRANCAASIrcsfoxKdOXRo61loXOxxDsSM8+eB
HHNh9NJEvQxk911CQcXi9FdQNocD2WtUJo28sEgp/6A/bmeIPpdEBIoZ
-----END PRIVATE KEY-----
"""
cert_issued_at = 1790441002
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:87fd:40c3:b04:12f4:1777"
wg_private_key = "IL9ADUK+salbxSrs6OQdKqcb7Hbd7NrqTbgPPJ3dOWI="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "p9ND"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.7"
