// app/lib/services/dns_directory_apac.dart
//
// Asia-Pacific public DNS providers. Source cited per entry.
// v2: added 360 Secure DNS regional pairs (China) and IIJ Public DNS
// (Japan) per the extension pass.

import '../models/dns_entry.dart';

// Asia-Pacific
final List<DnsEntry> kApacDnsDirectory = <DnsEntry>[
  DnsEntry(
    id: 'quad101-v4',
    name: 'Quad101 (TWNIC)',
    primary: '101.101.101.101',
    secondary: '101.102.103.104',
    country: 'TW',
    provider: 'TWNIC',
    tags: {DnsTag.unfiltered, DnsTag.dnssec, DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'TWNIC Quad101 official docs, 101.101.101.101 (Taiwan)',
  ),
  DnsEntry(
    id: 'quad101-v6',
    name: 'Quad101 (TWNIC) (IPv6)',
    primaryV6: '2001:de4::101',
    secondaryV6: '2001:de4::102',
    country: 'TW',
    provider: 'TWNIC',
    tags: {DnsTag.unfiltered, DnsTag.dnssec, DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'TWNIC Quad101 official docs, 101.101.101.101 (Taiwan)',
  ),
  DnsEntry(
    id: 'quad101-doh',
    name: 'Quad101 (TWNIC) (DoH)',
    dohUrl: 'https://dns.twnic.tw/dns-query',
    country: 'TW',
    provider: 'TWNIC',
    tags: {DnsTag.unfiltered, DnsTag.dnssec, DnsTag.geo},
    protocols: {DnsProtocol.doh},
    source: 'TWNIC Quad101 official docs, 101.101.101.101 (Taiwan)',
  ),
  DnsEntry(
    id: 'quad101-dot',
    name: 'Quad101 (TWNIC) (DoT)',
    dotHost: 'dns.twnic.tw',
    country: 'TW',
    provider: 'TWNIC',
    tags: {DnsTag.unfiltered, DnsTag.dnssec, DnsTag.geo},
    protocols: {DnsProtocol.dot},
    source: 'TWNIC Quad101 official docs, 101.101.101.101 (Taiwan)',
  ),
  DnsEntry(
    id: 'alidns-v4',
    name: 'AliDNS (Alibaba Cloud)',
    primary: '223.5.5.5',
    secondary: '223.6.6.6',
    country: 'CN',
    provider: 'Alibaba',
    tags: {DnsTag.unfiltered, DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Alibaba Cloud AliDNS official docs, alidns.com',
  ),
  DnsEntry(
    id: 'alidns-v6',
    name: 'AliDNS (Alibaba Cloud) (IPv6)',
    primaryV6: '2400:3200::1',
    secondaryV6: '2400:3200:baba::1',
    country: 'CN',
    provider: 'Alibaba',
    tags: {DnsTag.unfiltered, DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Alibaba Cloud AliDNS official docs, alidns.com',
  ),
  DnsEntry(
    id: 'alidns-doh',
    name: 'AliDNS (Alibaba Cloud) (DoH)',
    dohUrl: 'https://dns.alidns.com/dns-query',
    country: 'CN',
    provider: 'Alibaba',
    tags: {DnsTag.unfiltered, DnsTag.geo},
    protocols: {DnsProtocol.doh},
    source: 'Alibaba Cloud AliDNS official docs, alidns.com',
  ),
  DnsEntry(
    id: 'alidns-dot',
    name: 'AliDNS (Alibaba Cloud) (DoT)',
    dotHost: 'dns.alidns.com',
    country: 'CN',
    provider: 'Alibaba',
    tags: {DnsTag.unfiltered, DnsTag.geo},
    protocols: {DnsProtocol.dot},
    source: 'Alibaba Cloud AliDNS official docs, alidns.com',
  ),
  DnsEntry(
    id: 'dnspod-v4',
    name: 'DNSPod Public DNS (Tencent)',
    primary: '119.29.29.29',
    secondary: '182.254.116.116',
    country: 'CN',
    provider: 'Tencent',
    tags: {DnsTag.unfiltered, DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Tencent Cloud DNSPod Public DNS, 119.29.29.29 (docs.dnspod.cn)',
  ),
  DnsEntry(
    id: 'dnspod-doh',
    name: 'DNSPod Public DNS (Tencent) (DoH)',
    dohUrl: 'https://dns.pub/dns-query',
    country: 'CN',
    provider: 'Tencent',
    tags: {DnsTag.unfiltered, DnsTag.geo},
    protocols: {DnsProtocol.doh},
    source: 'Tencent Cloud DNSPod Public DNS, 119.29.29.29 (docs.dnspod.cn)',
  ),
  DnsEntry(
    id: '114dns-v4',
    name: '114DNS',
    primary: '114.114.114.114',
    secondary: '114.114.115.115',
    country: 'CN',
    provider: '114DNS',
    tags: {DnsTag.unfiltered, DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: '114DNS, long-standing public China resolver, 114dns.com',
  ),
  DnsEntry(
    id: 'baidu-v4',
    name: 'Baidu Public DNS',
    primary: '180.76.76.76',
    country: 'CN',
    provider: 'Baidu',
    tags: {DnsTag.unfiltered, DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Baidu Public DNS, 180.76.76.76 + IPv6 (widely documented)',
  ),
  DnsEntry(
    id: 'baidu-v6',
    name: 'Baidu Public DNS (IPv6)',
    primaryV6: '2400:da00::6666',
    country: 'CN',
    provider: 'Baidu',
    tags: {DnsTag.unfiltered, DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Baidu Public DNS, 180.76.76.76 + IPv6 (widely documented)',
  ),
  DnsEntry(
    id: '360-telecom-v4',
    name: '360 Secure DNS (China Telecom/Mobile)',
    primary: '101.226.4.6',
    secondary: '218.30.118.6',
    country: 'CN',
    provider: '360',
    tags: {DnsTag.blocking, DnsTag.security, DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: '360 Security DNS, dot.360.cn / doh.360.cn (community-verified regional IPv4 sets, China)',
  ),
  DnsEntry(
    id: '360-telecom-doh',
    name: '360 Secure DNS (China Telecom/Mobile) (DoH)',
    dohUrl: 'https://doh.360.cn',
    country: 'CN',
    provider: '360',
    tags: {DnsTag.blocking, DnsTag.security, DnsTag.geo},
    protocols: {DnsProtocol.doh},
    source: '360 Security DNS, dot.360.cn / doh.360.cn (community-verified regional IPv4 sets, China)',
  ),
  DnsEntry(
    id: '360-telecom-dot',
    name: '360 Secure DNS (China Telecom/Mobile) (DoT)',
    dotHost: 'dot.360.cn',
    country: 'CN',
    provider: '360',
    tags: {DnsTag.blocking, DnsTag.security, DnsTag.geo},
    protocols: {DnsProtocol.dot},
    source: '360 Security DNS, dot.360.cn / doh.360.cn (community-verified regional IPv4 sets, China)',
  ),
  DnsEntry(
    id: '360-unicom-v4',
    name: '360 Secure DNS (China Unicom)',
    primary: '123.125.81.6',
    secondary: '140.207.198.6',
    country: 'CN',
    provider: '360',
    tags: {DnsTag.blocking, DnsTag.security, DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: '360 Security DNS, dot.360.cn / doh.360.cn (community-verified regional IPv4 sets, China)',
  ),
  DnsEntry(
    id: 'iij-v6',
    name: 'IIJ Public DNS (IPv6)',
    primaryV6: '2001:300::5',
    secondaryV6: '2001:300::6',
    country: 'JP',
    provider: 'IIJ',
    tags: {DnsTag.unfiltered, DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'IIJ Public DNS official docs, public.dns.iij.jp (Japan)',
  ),
  DnsEntry(
    id: 'iij-doh',
    name: 'IIJ Public DNS (DoH)',
    dohUrl: 'https://public.dns.iij.jp/dns-query',
    country: 'JP',
    provider: 'IIJ',
    tags: {DnsTag.unfiltered, DnsTag.geo},
    protocols: {DnsProtocol.doh},
    source: 'IIJ Public DNS official docs, public.dns.iij.jp (Japan)',
  ),
  DnsEntry(
    id: 'iij-dot',
    name: 'IIJ Public DNS (DoT)',
    dotHost: 'public.dns.iij.jp',
    country: 'JP',
    provider: 'IIJ',
    tags: {DnsTag.unfiltered, DnsTag.geo},
    protocols: {DnsProtocol.dot},
    source: 'IIJ Public DNS official docs, public.dns.iij.jp (Japan)',
  ),
];
