// app/lib/services/dns_directory_us.dart
//
// US-headquartered / global-anycast public DNS providers.
// Each base resolver is split into up to 4 DnsEntry rows (IPv4 pair,
// IPv6 pair, DoH, DoT) — same underlying service, different transport,
// per the plan confirmed with the user. Source cited per entry.
// v2: added ControlD's 3 additional free presets (p1/p2/p3) with
// their DoH/DoT endpoints, per user's extension-pass request.

import '../models/dns_entry.dart';

// US / global-anycast providers
final List<DnsEntry> kUsDnsDirectory = <DnsEntry>[
  DnsEntry(
    id: 'cf-unfiltered-v4',
    name: 'Cloudflare · Unfiltered',
    primary: '1.1.1.1',
    secondary: '1.0.0.1',
    country: 'US',
    provider: 'Cloudflare',
    tags: {DnsTag.anycast, DnsTag.unfiltered, DnsTag.dnssec},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Cloudflare official docs, developers.cloudflare.com/1.1.1.1 (2026)',
  ),
  DnsEntry(
    id: 'cf-unfiltered-v6',
    name: 'Cloudflare · Unfiltered (IPv6)',
    primaryV6: '2606:4700:4700::1111',
    secondaryV6: '2606:4700:4700::1001',
    country: 'US',
    provider: 'Cloudflare',
    tags: {DnsTag.anycast, DnsTag.unfiltered, DnsTag.dnssec},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Cloudflare official docs, developers.cloudflare.com/1.1.1.1 (2026)',
  ),
  DnsEntry(
    id: 'cf-unfiltered-doh',
    name: 'Cloudflare · Unfiltered (DoH)',
    dohUrl: 'https://cloudflare-dns.com/dns-query',
    country: 'US',
    provider: 'Cloudflare',
    tags: {DnsTag.anycast, DnsTag.unfiltered, DnsTag.dnssec},
    protocols: {DnsProtocol.doh},
    source: 'Cloudflare official docs, developers.cloudflare.com/1.1.1.1 (2026)',
  ),
  DnsEntry(
    id: 'cf-unfiltered-dot',
    name: 'Cloudflare · Unfiltered (DoT)',
    dotHost: '1dot1dot1dot1.cloudflare-dns.com',
    country: 'US',
    provider: 'Cloudflare',
    tags: {DnsTag.anycast, DnsTag.unfiltered, DnsTag.dnssec},
    protocols: {DnsProtocol.dot},
    source: 'Cloudflare official docs, developers.cloudflare.com/1.1.1.1 (2026)',
  ),
  DnsEntry(
    id: 'cf-malware-v4',
    name: 'Cloudflare · Malware Block',
    primary: '1.1.1.2',
    secondary: '1.0.0.2',
    country: 'US',
    provider: 'Cloudflare',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.dnssec},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Cloudflare official docs, developers.cloudflare.com/1.1.1.1 (2026)',
  ),
  DnsEntry(
    id: 'cf-malware-v6',
    name: 'Cloudflare · Malware Block (IPv6)',
    primaryV6: '2606:4700:4700::1112',
    secondaryV6: '2606:4700:4700::1002',
    country: 'US',
    provider: 'Cloudflare',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.dnssec},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Cloudflare official docs, developers.cloudflare.com/1.1.1.1 (2026)',
  ),
  DnsEntry(
    id: 'cf-family-v4',
    name: 'Cloudflare · Family (Malware+Adult)',
    primary: '1.1.1.3',
    secondary: '1.0.0.3',
    country: 'US',
    provider: 'Cloudflare',
    tags: {DnsTag.anycast, DnsTag.family, DnsTag.blocking, DnsTag.dnssec},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Cloudflare official docs, developers.cloudflare.com/1.1.1.1 (2026)',
  ),
  DnsEntry(
    id: 'cf-family-v6',
    name: 'Cloudflare · Family (Malware+Adult) (IPv6)',
    primaryV6: '2606:4700:4700::1113',
    secondaryV6: '2606:4700:4700::1003',
    country: 'US',
    provider: 'Cloudflare',
    tags: {DnsTag.anycast, DnsTag.family, DnsTag.blocking, DnsTag.dnssec},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Cloudflare official docs, developers.cloudflare.com/1.1.1.1 (2026)',
  ),
  DnsEntry(
    id: 'google-public-v4',
    name: 'Google Public DNS',
    primary: '8.8.8.8',
    secondary: '8.8.4.4',
    country: 'US',
    provider: 'Google',
    tags: {DnsTag.anycast, DnsTag.unfiltered, DnsTag.dnssec},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Google Public DNS official docs, developers.google.com/speed/public-dns (2026)',
  ),
  DnsEntry(
    id: 'google-public-v6',
    name: 'Google Public DNS (IPv6)',
    primaryV6: '2001:4860:4860::8888',
    secondaryV6: '2001:4860:4860::8844',
    country: 'US',
    provider: 'Google',
    tags: {DnsTag.anycast, DnsTag.unfiltered, DnsTag.dnssec},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Google Public DNS official docs, developers.google.com/speed/public-dns (2026)',
  ),
  DnsEntry(
    id: 'google-public-doh',
    name: 'Google Public DNS (DoH)',
    dohUrl: 'https://dns.google/dns-query',
    country: 'US',
    provider: 'Google',
    tags: {DnsTag.anycast, DnsTag.unfiltered, DnsTag.dnssec},
    protocols: {DnsProtocol.doh},
    source: 'Google Public DNS official docs, developers.google.com/speed/public-dns (2026)',
  ),
  DnsEntry(
    id: 'google-public-dot',
    name: 'Google Public DNS (DoT)',
    dotHost: 'dns.google',
    country: 'US',
    provider: 'Google',
    tags: {DnsTag.anycast, DnsTag.unfiltered, DnsTag.dnssec},
    protocols: {DnsProtocol.dot},
    source: 'Google Public DNS official docs, developers.google.com/speed/public-dns (2026)',
  ),
  DnsEntry(
    id: 'quad9-secured-v4',
    name: 'Quad9 · Secured (Malware Block)',
    primary: '9.9.9.9',
    secondary: '149.112.112.112',
    country: 'US',
    provider: 'Quad9',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.dnssec, DnsTag.security},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Quad9 official docs, quad9.net (2026)',
  ),
  DnsEntry(
    id: 'quad9-secured-v6',
    name: 'Quad9 · Secured (Malware Block) (IPv6)',
    primaryV6: '2620:fe::fe',
    secondaryV6: '2620:fe::9',
    country: 'US',
    provider: 'Quad9',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.dnssec, DnsTag.security},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Quad9 official docs, quad9.net (2026)',
  ),
  DnsEntry(
    id: 'quad9-secured-doh',
    name: 'Quad9 · Secured (Malware Block) (DoH)',
    dohUrl: 'https://dns.quad9.net/dns-query',
    country: 'US',
    provider: 'Quad9',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.dnssec, DnsTag.security},
    protocols: {DnsProtocol.doh},
    source: 'Quad9 official docs, quad9.net (2026)',
  ),
  DnsEntry(
    id: 'quad9-secured-dot',
    name: 'Quad9 · Secured (Malware Block) (DoT)',
    dotHost: 'dns.quad9.net',
    country: 'US',
    provider: 'Quad9',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.dnssec, DnsTag.security},
    protocols: {DnsProtocol.dot},
    source: 'Quad9 official docs, quad9.net (2026)',
  ),
  DnsEntry(
    id: 'quad9-unsecured-v4',
    name: 'Quad9 · Unsecured (No Filtering)',
    primary: '9.9.9.10',
    secondary: '149.112.112.10',
    country: 'US',
    provider: 'Quad9',
    tags: {DnsTag.anycast, DnsTag.unfiltered},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Quad9 official docs, quad9.net (2026)',
  ),
  DnsEntry(
    id: 'quad9-unsecured-v6',
    name: 'Quad9 · Unsecured (No Filtering) (IPv6)',
    primaryV6: '2620:fe::10',
    secondaryV6: '2620:fe::fe:10',
    country: 'US',
    provider: 'Quad9',
    tags: {DnsTag.anycast, DnsTag.unfiltered},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Quad9 official docs, quad9.net (2026)',
  ),
  DnsEntry(
    id: 'quad9-ecs-v4',
    name: 'Quad9 · ECS-enabled',
    primary: '9.9.9.11',
    secondary: '149.112.112.11',
    country: 'US',
    provider: 'Quad9',
    tags: {DnsTag.anycast, DnsTag.dnssec, DnsTag.ecs, DnsTag.blocking},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Quad9 official docs, quad9.net (2026)',
  ),
  DnsEntry(
    id: 'quad9-ecs-v6',
    name: 'Quad9 · ECS-enabled (IPv6)',
    primaryV6: '2620:fe::11',
    country: 'US',
    provider: 'Quad9',
    tags: {DnsTag.anycast, DnsTag.dnssec, DnsTag.ecs, DnsTag.blocking},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Quad9 official docs, quad9.net (2026)',
  ),
  DnsEntry(
    id: 'opendns-std-v4',
    name: 'OpenDNS (Cisco Umbrella)',
    primary: '208.67.222.222',
    secondary: '208.67.220.220',
    country: 'US',
    provider: 'OpenDNS',
    tags: {DnsTag.anycast, DnsTag.unfiltered},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Cisco OpenDNS / Umbrella official docs, opendns.com (2026)',
  ),
  DnsEntry(
    id: 'opendns-std-v6',
    name: 'OpenDNS (Cisco Umbrella) (IPv6)',
    primaryV6: '2620:119:35::35',
    secondaryV6: '2620:119:53::53',
    country: 'US',
    provider: 'OpenDNS',
    tags: {DnsTag.anycast, DnsTag.unfiltered},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Cisco OpenDNS / Umbrella official docs, opendns.com (2026)',
  ),
  DnsEntry(
    id: 'opendns-std-doh',
    name: 'OpenDNS (Cisco Umbrella) (DoH)',
    dohUrl: 'https://doh.opendns.com/dns-query',
    country: 'US',
    provider: 'OpenDNS',
    tags: {DnsTag.anycast, DnsTag.unfiltered},
    protocols: {DnsProtocol.doh},
    source: 'Cisco OpenDNS / Umbrella official docs, opendns.com (2026)',
  ),
  DnsEntry(
    id: 'opendns-family-v4',
    name: 'OpenDNS · FamilyShield',
    primary: '208.67.222.123',
    secondary: '208.67.220.123',
    country: 'US',
    provider: 'OpenDNS',
    tags: {DnsTag.anycast, DnsTag.family, DnsTag.blocking},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Cisco OpenDNS / Umbrella official docs, opendns.com (2026)',
  ),
  DnsEntry(
    id: 'opendns-family-doh',
    name: 'OpenDNS · FamilyShield (DoH)',
    dohUrl: 'https://doh.familyshield.opendns.com/dns-query',
    country: 'US',
    provider: 'OpenDNS',
    tags: {DnsTag.anycast, DnsTag.family, DnsTag.blocking},
    protocols: {DnsProtocol.doh},
    source: 'Cisco OpenDNS / Umbrella official docs, opendns.com (2026)',
  ),
  DnsEntry(
    id: 'controld-unfiltered-v4',
    name: 'ControlD · Unfiltered (p0)',
    primary: '76.76.2.0',
    secondary: '76.76.10.0',
    country: 'US',
    provider: 'ControlD',
    tags: {DnsTag.anycast, DnsTag.unfiltered},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'ControlD Free DNS docs, controld.com/free-dns + docs.controld.com/docs/free-dns (2026)',
  ),
  DnsEntry(
    id: 'controld-unfiltered-doh',
    name: 'ControlD · Unfiltered (p0) (DoH)',
    dohUrl: 'https://freedns.controld.com/p0',
    country: 'US',
    provider: 'ControlD',
    tags: {DnsTag.anycast, DnsTag.unfiltered},
    protocols: {DnsProtocol.doh},
    source: 'ControlD Free DNS docs, controld.com/free-dns + docs.controld.com/docs/free-dns (2026)',
  ),
  DnsEntry(
    id: 'controld-unfiltered-dot',
    name: 'ControlD · Unfiltered (p0) (DoT)',
    dotHost: 'p0.freedns.controld.com',
    country: 'US',
    provider: 'ControlD',
    tags: {DnsTag.anycast, DnsTag.unfiltered},
    protocols: {DnsProtocol.dot},
    source: 'ControlD Free DNS docs, controld.com/free-dns + docs.controld.com/docs/free-dns (2026)',
  ),
  DnsEntry(
    id: 'controld-malware-v4',
    name: 'ControlD · Block Malware (p1)',
    primary: '76.76.2.1',
    secondary: '76.76.10.1',
    country: 'US',
    provider: 'ControlD',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.security},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'ControlD Free DNS docs, controld.com/free-dns + docs.controld.com/docs/free-dns (2026)',
  ),
  DnsEntry(
    id: 'controld-malware-doh',
    name: 'ControlD · Block Malware (p1) (DoH)',
    dohUrl: 'https://freedns.controld.com/p1',
    country: 'US',
    provider: 'ControlD',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.security},
    protocols: {DnsProtocol.doh},
    source: 'ControlD Free DNS docs, controld.com/free-dns + docs.controld.com/docs/free-dns (2026)',
  ),
  DnsEntry(
    id: 'controld-malware-dot',
    name: 'ControlD · Block Malware (p1) (DoT)',
    dotHost: 'p1.freedns.controld.com',
    country: 'US',
    provider: 'ControlD',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.security},
    protocols: {DnsProtocol.dot},
    source: 'ControlD Free DNS docs, controld.com/free-dns + docs.controld.com/docs/free-dns (2026)',
  ),
  DnsEntry(
    id: 'controld-malware-ads-v4',
    name: 'ControlD · Block Malware+Ads (p2)',
    primary: '76.76.2.2',
    secondary: '76.76.10.2',
    country: 'US',
    provider: 'ControlD',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.security},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'ControlD Free DNS docs, controld.com/free-dns + docs.controld.com/docs/free-dns (2026)',
  ),
  DnsEntry(
    id: 'controld-malware-ads-doh',
    name: 'ControlD · Block Malware+Ads (p2) (DoH)',
    dohUrl: 'https://freedns.controld.com/p2',
    country: 'US',
    provider: 'ControlD',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.security},
    protocols: {DnsProtocol.doh},
    source: 'ControlD Free DNS docs, controld.com/free-dns + docs.controld.com/docs/free-dns (2026)',
  ),
  DnsEntry(
    id: 'controld-malware-ads-dot',
    name: 'ControlD · Block Malware+Ads (p2) (DoT)',
    dotHost: 'p2.freedns.controld.com',
    country: 'US',
    provider: 'ControlD',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.security},
    protocols: {DnsProtocol.dot},
    source: 'ControlD Free DNS docs, controld.com/free-dns + docs.controld.com/docs/free-dns (2026)',
  ),
  DnsEntry(
    id: 'controld-malware-ads-social-v4',
    name: 'ControlD · Block Malware+Ads+Social (p3)',
    primary: '76.76.2.3',
    secondary: '76.76.10.3',
    country: 'US',
    provider: 'ControlD',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.security},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'ControlD Free DNS docs, controld.com/free-dns + docs.controld.com/docs/free-dns (2026)',
  ),
  DnsEntry(
    id: 'controld-malware-ads-social-doh',
    name: 'ControlD · Block Malware+Ads+Social (p3) (DoH)',
    dohUrl: 'https://freedns.controld.com/p3',
    country: 'US',
    provider: 'ControlD',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.security},
    protocols: {DnsProtocol.doh},
    source: 'ControlD Free DNS docs, controld.com/free-dns + docs.controld.com/docs/free-dns (2026)',
  ),
  DnsEntry(
    id: 'controld-malware-ads-social-dot',
    name: 'ControlD · Block Malware+Ads+Social (p3) (DoT)',
    dotHost: 'p3.freedns.controld.com',
    country: 'US',
    provider: 'ControlD',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.security},
    protocols: {DnsProtocol.dot},
    source: 'ControlD Free DNS docs, controld.com/free-dns + docs.controld.com/docs/free-dns (2026)',
  ),
  DnsEntry(
    id: 'cleanbrowsing-family-v4',
    name: 'CleanBrowsing · Family Filter',
    primary: '185.228.168.168',
    secondary: '185.228.169.168',
    country: 'US',
    provider: 'CleanBrowsing',
    tags: {DnsTag.anycast, DnsTag.family, DnsTag.blocking},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'CleanBrowsing official docs, cleanbrowsing.org/filters (2026)',
  ),
  DnsEntry(
    id: 'cleanbrowsing-family-v6',
    name: 'CleanBrowsing · Family Filter (IPv6)',
    primaryV6: '2a0d:2a00:1::',
    secondaryV6: '2a0d:2a00:2::',
    country: 'US',
    provider: 'CleanBrowsing',
    tags: {DnsTag.anycast, DnsTag.family, DnsTag.blocking},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'CleanBrowsing official docs, cleanbrowsing.org/filters (2026)',
  ),
  DnsEntry(
    id: 'cleanbrowsing-family-doh',
    name: 'CleanBrowsing · Family Filter (DoH)',
    dohUrl: 'https://doh.cleanbrowsing.org/doh/family-filter/',
    country: 'US',
    provider: 'CleanBrowsing',
    tags: {DnsTag.anycast, DnsTag.family, DnsTag.blocking},
    protocols: {DnsProtocol.doh},
    source: 'CleanBrowsing official docs, cleanbrowsing.org/filters (2026)',
  ),
  DnsEntry(
    id: 'cleanbrowsing-adult-v4',
    name: 'CleanBrowsing · Adult Filter',
    primary: '185.228.168.10',
    secondary: '185.228.169.11',
    country: 'US',
    provider: 'CleanBrowsing',
    tags: {DnsTag.anycast, DnsTag.blocking},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'CleanBrowsing official docs, cleanbrowsing.org/filters (2026)',
  ),
  DnsEntry(
    id: 'cleanbrowsing-adult-v6',
    name: 'CleanBrowsing · Adult Filter (IPv6)',
    primaryV6: '2a0d:2a00:1::1',
    secondaryV6: '2a0d:2a00:2::1',
    country: 'US',
    provider: 'CleanBrowsing',
    tags: {DnsTag.anycast, DnsTag.blocking},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'CleanBrowsing official docs, cleanbrowsing.org/filters (2026)',
  ),
  DnsEntry(
    id: 'cleanbrowsing-adult-doh',
    name: 'CleanBrowsing · Adult Filter (DoH)',
    dohUrl: 'https://doh.cleanbrowsing.org/doh/adult-filter/',
    country: 'US',
    provider: 'CleanBrowsing',
    tags: {DnsTag.anycast, DnsTag.blocking},
    protocols: {DnsProtocol.doh},
    source: 'CleanBrowsing official docs, cleanbrowsing.org/filters (2026)',
  ),
  DnsEntry(
    id: 'cleanbrowsing-security-v4',
    name: 'CleanBrowsing · Security Filter',
    primary: '185.228.168.9',
    secondary: '185.228.169.9',
    country: 'US',
    provider: 'CleanBrowsing',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.security},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'CleanBrowsing official docs, cleanbrowsing.org/filters (2026)',
  ),
  DnsEntry(
    id: 'cleanbrowsing-security-doh',
    name: 'CleanBrowsing · Security Filter (DoH)',
    dohUrl: 'https://doh.cleanbrowsing.org/doh/security-filter/',
    country: 'US',
    provider: 'CleanBrowsing',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.security},
    protocols: {DnsProtocol.doh},
    source: 'CleanBrowsing official docs, cleanbrowsing.org/filters (2026)',
  ),
  DnsEntry(
    id: 'verisign-v4',
    name: 'Verisign Public DNS',
    primary: '64.6.64.6',
    secondary: '64.6.65.6',
    country: 'US',
    provider: 'Verisign',
    tags: {DnsTag.anycast, DnsTag.unfiltered, DnsTag.dnssec},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Verisign Public DNS, publicdns.verisign.com (long-standing, stable)',
  ),
  DnsEntry(
    id: 'comodo-secure-v4',
    name: 'Comodo Secure DNS',
    primary: '8.26.56.26',
    secondary: '8.20.247.20',
    country: 'US',
    provider: 'Comodo',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.security},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Comodo Secure DNS, dns.comodo.com (long-standing, stable)',
  ),
  DnsEntry(
    id: 'level3-v4',
    name: 'Level3 / Lumen Open Resolvers',
    primary: '4.2.2.1',
    secondary: '4.2.2.2',
    country: 'US',
    provider: 'Lumen (Level3)',
    tags: {DnsTag.anycast, DnsTag.unfiltered},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Level3/Lumen legacy open resolvers, widely documented (4.2.2.x)',
  ),
  DnsEntry(
    id: 'ultradns-recursive-v4',
    name: 'UltraDNS · Public Recursive',
    primary: '156.154.70.1',
    secondary: '156.154.71.1',
    country: 'US',
    provider: 'Neustar UltraDNS',
    tags: {DnsTag.anycast, DnsTag.unfiltered},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Neustar UltraDNS public recursive/threat-protection resolvers',
  ),
  DnsEntry(
    id: 'ultradns-threat-v4',
    name: 'UltraDNS · Threat Protection',
    primary: '156.154.70.2',
    secondary: '156.154.71.2',
    country: 'US',
    provider: 'Neustar UltraDNS',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.security},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Neustar UltraDNS public recursive/threat-protection resolvers',
  ),
];
