// app/lib/services/dns_directory_other.dart
//
// Everything that doesn't fit the US / EU / APAC / IR buckets cleanly
// (Russia, Canada, multi-region privacy projects, Gcore, and OpenNIC's
// volunteer tier-2 nodes). Source cited per entry.
//
// IMPORTANT: the OpenNIC entries below are individually-run volunteer
// nodes, not a commercial anycast network. They're real, documented
// addresses (see source string) but are meaningfully less reliable
// long-term than the rest of this directory — the UI should treat
// provider == 'OpenNIC (volunteer)' as lower-confidence (e.g. exclude
// from "auto-select best" unless the user opts in).

import '../models/dns_entry.dart';

// Other regions
final List<DnsEntry> kOtherDnsDirectory = <DnsEntry>[
  DnsEntry(
    id: 'yandex-basic-v4',
    name: 'Yandex DNS · Basic',
    primary: '77.88.8.8',
    secondary: '77.88.8.1',
    country: 'RU',
    provider: 'Yandex',
    tags: {DnsTag.unfiltered, DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Yandex DNS official docs, yandex.com/support/dns (long-standing, stable)',
  ),
  DnsEntry(
    id: 'yandex-safe-v4',
    name: 'Yandex DNS · Safe (Malware Block)',
    primary: '77.88.8.88',
    secondary: '77.88.8.2',
    country: 'RU',
    provider: 'Yandex',
    tags: {DnsTag.blocking, DnsTag.security, DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Yandex DNS official docs, yandex.com/support/dns (long-standing, stable)',
  ),
  DnsEntry(
    id: 'yandex-family-v4',
    name: 'Yandex DNS · Family',
    primary: '77.88.8.7',
    secondary: '77.88.8.3',
    country: 'RU',
    provider: 'Yandex',
    tags: {DnsTag.family, DnsTag.blocking, DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Yandex DNS official docs, yandex.com/support/dns (long-standing, stable)',
  ),
  DnsEntry(
    id: 'cira-protected-doh',
    name: 'CIRA Canadian Shield · Protected (DoH)',
    dohUrl: 'https://protected.canadianshield.cira.ca/dns-query',
    country: 'CA',
    provider: 'CIRA',
    tags: {DnsTag.blocking, DnsTag.security},
    protocols: {DnsProtocol.doh},
    source: 'CIRA Canadian Shield official docs, cira.ca/canadian-shield (DoH hostnames verified)',
  ),
  DnsEntry(
    id: 'cira-family-doh',
    name: 'CIRA Canadian Shield · Family (DoH)',
    dohUrl: 'https://family.canadianshield.cira.ca/dns-query',
    country: 'CA',
    provider: 'CIRA',
    tags: {DnsTag.family, DnsTag.blocking},
    protocols: {DnsProtocol.doh},
    source: 'CIRA Canadian Shield official docs, cira.ca/canadian-shield (DoH hostnames verified)',
  ),
  DnsEntry(
    id: 'cira-private-doh',
    name: 'CIRA Canadian Shield · Private (Unfiltered) (DoH)',
    dohUrl: 'https://private.canadianshield.cira.ca/dns-query',
    country: 'CA',
    provider: 'CIRA',
    tags: {DnsTag.unfiltered, DnsTag.privacy},
    protocols: {DnsProtocol.doh},
    source: 'CIRA Canadian Shield official docs, cira.ca/canadian-shield (DoH hostnames verified)',
  ),
  DnsEntry(
    id: 'blahdns-de-doh',
    name: 'BlahDNS · Germany (DoH)',
    dohUrl: 'https://doh-de.blahdns.com/dns-query',
    country: 'DE',
    provider: 'BlahDNS',
    tags: {DnsTag.blocking, DnsTag.privacy, DnsTag.geo},
    protocols: {DnsProtocol.doh},
    source: 'BlahDNS privacy resolver project, blahdns.com (multi-region DoH)',
  ),
  DnsEntry(
    id: 'blahdns-jp-doh',
    name: 'BlahDNS · Japan (DoH)',
    dohUrl: 'https://doh-jp.blahdns.com/dns-query',
    country: 'JP',
    provider: 'BlahDNS',
    tags: {DnsTag.blocking, DnsTag.privacy, DnsTag.geo},
    protocols: {DnsProtocol.doh},
    source: 'BlahDNS privacy resolver project, blahdns.com (multi-region DoH)',
  ),
  DnsEntry(
    id: 'blahdns-sg-doh',
    name: 'BlahDNS · Singapore (DoH)',
    dohUrl: 'https://doh-sg.blahdns.com/dns-query',
    country: 'SG',
    provider: 'BlahDNS',
    tags: {DnsTag.blocking, DnsTag.privacy, DnsTag.geo},
    protocols: {DnsProtocol.doh},
    source: 'BlahDNS privacy resolver project, blahdns.com (multi-region DoH)',
  ),
  DnsEntry(
    id: 'gcore-v4',
    name: 'Gcore Public DNS',
    primary: '95.85.95.85',
    secondary: '2.56.220.2',
    country: 'LU',
    provider: 'Gcore',
    tags: {DnsTag.anycast, DnsTag.unfiltered, DnsTag.dnssec},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Gcore Public DNS official docs, docs.gcore.com/dns/public-dns',
  ),
  DnsEntry(
    id: 'gcore-v6',
    name: 'Gcore Public DNS (IPv6)',
    primaryV6: '2a03:90c0:999d::1',
    secondaryV6: '2a03:90c0:9992::1',
    country: 'LU',
    provider: 'Gcore',
    tags: {DnsTag.anycast, DnsTag.unfiltered, DnsTag.dnssec},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Gcore Public DNS official docs, docs.gcore.com/dns/public-dns',
  ),
  DnsEntry(
    id: 'opennic-1-v4',
    name: 'OpenNIC Tier-2 · Node A',
    primary: '202.83.95.227',
    country: 'ZZ',
    provider: 'OpenNIC (volunteer)',
    tags: {DnsTag.unfiltered},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'OpenNIC Tier-2 volunteer public-access servers, published via the OpenNIC wiki / community mirrors (ab9il.net open-free-dns list). CAVEAT: these are individually run, non-commercial volunteer nodes — addresses rotate more than commercial providers and a given node can go offline without notice. Kept as a distinct, clearly-tagged bucket rather than blended into the \'reliable\' entries.',
  ),
  DnsEntry(
    id: 'opennic-2-v4',
    name: 'OpenNIC Tier-2 · Node B',
    primary: '119.31.230.42',
    country: 'ZZ',
    provider: 'OpenNIC (volunteer)',
    tags: {DnsTag.unfiltered},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'OpenNIC Tier-2 volunteer public-access servers, published via the OpenNIC wiki / community mirrors (ab9il.net open-free-dns list). CAVEAT: these are individually run, non-commercial volunteer nodes — addresses rotate more than commercial providers and a given node can go offline without notice. Kept as a distinct, clearly-tagged bucket rather than blended into the \'reliable\' entries.',
  ),
  DnsEntry(
    id: 'opennic-3-v4',
    name: 'OpenNIC Tier-2 · Node C',
    primary: '178.63.26.173',
    country: 'ZZ',
    provider: 'OpenNIC (volunteer)',
    tags: {DnsTag.unfiltered},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'OpenNIC Tier-2 volunteer public-access servers, published via the OpenNIC wiki / community mirrors (ab9il.net open-free-dns list). CAVEAT: these are individually run, non-commercial volunteer nodes — addresses rotate more than commercial providers and a given node can go offline without notice. Kept as a distinct, clearly-tagged bucket rather than blended into the \'reliable\' entries.',
  ),
  DnsEntry(
    id: 'opennic-4-v4',
    name: 'OpenNIC Tier-2 · Node D',
    primary: '217.79.186.148',
    country: 'ZZ',
    provider: 'OpenNIC (volunteer)',
    tags: {DnsTag.unfiltered},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'OpenNIC Tier-2 volunteer public-access servers, published via the OpenNIC wiki / community mirrors (ab9il.net open-free-dns list). CAVEAT: these are individually run, non-commercial volunteer nodes — addresses rotate more than commercial providers and a given node can go offline without notice. Kept as a distinct, clearly-tagged bucket rather than blended into the \'reliable\' entries.',
  ),
  DnsEntry(
    id: 'opennic-5-v4',
    name: 'OpenNIC Tier-2 · Node E',
    primary: '27.110.120.30',
    country: 'ZZ',
    provider: 'OpenNIC (volunteer)',
    tags: {DnsTag.unfiltered},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'OpenNIC Tier-2 volunteer public-access servers, published via the OpenNIC wiki / community mirrors (ab9il.net open-free-dns list). CAVEAT: these are individually run, non-commercial volunteer nodes — addresses rotate more than commercial providers and a given node can go offline without notice. Kept as a distinct, clearly-tagged bucket rather than blended into the \'reliable\' entries.',
  ),
  DnsEntry(
    id: 'opennic-6-v4',
    name: 'OpenNIC Tier-2 · Node F',
    primary: '89.16.173.11',
    country: 'ZZ',
    provider: 'OpenNIC (volunteer)',
    tags: {DnsTag.unfiltered},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'OpenNIC Tier-2 volunteer public-access servers, published via the OpenNIC wiki / community mirrors (ab9il.net open-free-dns list). CAVEAT: these are individually run, non-commercial volunteer nodes — addresses rotate more than commercial providers and a given node can go offline without notice. Kept as a distinct, clearly-tagged bucket rather than blended into the \'reliable\' entries.',
  ),
  DnsEntry(
    id: 'opennic-7-v4',
    name: 'OpenNIC Tier-2 · Node G',
    primary: '69.164.208.50',
    country: 'US',
    provider: 'OpenNIC (volunteer)',
    tags: {DnsTag.unfiltered},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'OpenNIC Tier-2 volunteer public-access servers, published via the OpenNIC wiki / community mirrors (ab9il.net open-free-dns list). CAVEAT: these are individually run, non-commercial volunteer nodes — addresses rotate more than commercial providers and a given node can go offline without notice. Kept as a distinct, clearly-tagged bucket rather than blended into the \'reliable\' entries.',
  ),
  DnsEntry(
    id: 'opennic-8-v4',
    name: 'OpenNIC Tier-2 · Node H',
    primary: '216.87.84.211',
    country: 'ZZ',
    provider: 'OpenNIC (volunteer)',
    tags: {DnsTag.unfiltered},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'OpenNIC Tier-2 volunteer public-access servers, published via the OpenNIC wiki / community mirrors (ab9il.net open-free-dns list). CAVEAT: these are individually run, non-commercial volunteer nodes — addresses rotate more than commercial providers and a given node can go offline without notice. Kept as a distinct, clearly-tagged bucket rather than blended into the \'reliable\' entries.',
  ),
  DnsEntry(
    id: 'opennic-8-v6',
    name: 'OpenNIC Tier-2 · Node H (IPv6)',
    primaryV6: '2001:470:8388:10:0:100:53:20',
    country: 'ZZ',
    provider: 'OpenNIC (volunteer)',
    tags: {DnsTag.unfiltered},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'OpenNIC Tier-2 volunteer public-access servers, published via the OpenNIC wiki / community mirrors (ab9il.net open-free-dns list). CAVEAT: these are individually run, non-commercial volunteer nodes — addresses rotate more than commercial providers and a given node can go offline without notice. Kept as a distinct, clearly-tagged bucket rather than blended into the \'reliable\' entries.',
  ),
];
