// app/lib/services/dns_directory_eu.dart
//
// Europe-based public DNS providers / projects. Source cited per entry.
// v2: added DNS4EU's remaining 4 published profiles (child/noads/
// child+noads/unfiltered) plus DNS.SB, FFMUC, dnsforge.de, Digitale
// Gesellschaft (CH) and Digitalcourage (DE, DoT-only) — all requested
// non-profit/privacy German-speaking resolvers, per the extension pass.

import '../models/dns_entry.dart';

// Europe
final List<DnsEntry> kEuDnsDirectory = <DnsEntry>[
  DnsEntry(
    id: 'adguard-default-v4',
    name: 'AdGuard DNS · Default (Ad Block)',
    primary: '94.140.14.14',
    secondary: '94.140.15.15',
    country: 'CY',
    provider: 'AdGuard',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.dnssec},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'AdGuard DNS official docs, adguard-dns.io (2026)',
  ),
  DnsEntry(
    id: 'adguard-default-v6',
    name: 'AdGuard DNS · Default (Ad Block) (IPv6)',
    primaryV6: '2a10:50c0::ad1:ff',
    secondaryV6: '2a10:50c0::ad2:ff',
    country: 'CY',
    provider: 'AdGuard',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.dnssec},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'AdGuard DNS official docs, adguard-dns.io (2026)',
  ),
  DnsEntry(
    id: 'adguard-default-doh',
    name: 'AdGuard DNS · Default (Ad Block) (DoH)',
    dohUrl: 'https://dns.adguard-dns.com/dns-query',
    country: 'CY',
    provider: 'AdGuard',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.dnssec},
    protocols: {DnsProtocol.doh},
    source: 'AdGuard DNS official docs, adguard-dns.io (2026)',
  ),
  DnsEntry(
    id: 'adguard-default-dot',
    name: 'AdGuard DNS · Default (Ad Block) (DoT)',
    dotHost: 'dns.adguard-dns.com',
    country: 'CY',
    provider: 'AdGuard',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.dnssec},
    protocols: {DnsProtocol.dot},
    source: 'AdGuard DNS official docs, adguard-dns.io (2026)',
  ),
  DnsEntry(
    id: 'adguard-family-v4',
    name: 'AdGuard DNS · Family Protection',
    primary: '94.140.14.15',
    secondary: '94.140.15.16',
    country: 'CY',
    provider: 'AdGuard',
    tags: {DnsTag.anycast, DnsTag.family, DnsTag.blocking},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'AdGuard DNS official docs, adguard-dns.io (2026)',
  ),
  DnsEntry(
    id: 'adguard-family-v6',
    name: 'AdGuard DNS · Family Protection (IPv6)',
    primaryV6: '2a10:50c0::bad1:ff',
    secondaryV6: '2a10:50c0::bad2:ff',
    country: 'CY',
    provider: 'AdGuard',
    tags: {DnsTag.anycast, DnsTag.family, DnsTag.blocking},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'AdGuard DNS official docs, adguard-dns.io (2026)',
  ),
  DnsEntry(
    id: 'adguard-unfiltered-v4',
    name: 'AdGuard DNS · Unfiltered',
    primary: '94.140.14.140',
    secondary: '94.140.14.141',
    country: 'CY',
    provider: 'AdGuard',
    tags: {DnsTag.anycast, DnsTag.unfiltered, DnsTag.dnssec},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'AdGuard DNS official docs, adguard-dns.io (2026)',
  ),
  DnsEntry(
    id: 'adguard-unfiltered-v6',
    name: 'AdGuard DNS · Unfiltered (IPv6)',
    primaryV6: '2a10:50c0::1:ff',
    secondaryV6: '2a10:50c0::2:ff',
    country: 'CY',
    provider: 'AdGuard',
    tags: {DnsTag.anycast, DnsTag.unfiltered, DnsTag.dnssec},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'AdGuard DNS official docs, adguard-dns.io (2026)',
  ),
  DnsEntry(
    id: 'dns0-default-v4',
    name: 'dns0.eu · Default (Malware Block)',
    primary: '193.110.81.0',
    secondary: '185.253.5.0',
    country: 'EU',
    provider: 'dns0.eu',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.dnssec, DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'dns0.eu official docs + community-verified addresses, dns0.eu (2026)',
  ),
  DnsEntry(
    id: 'dns0-default-v6',
    name: 'dns0.eu · Default (Malware Block) (IPv6)',
    primaryV6: '2a0f:fc80::',
    secondaryV6: '2a0f:fc81::',
    country: 'EU',
    provider: 'dns0.eu',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.dnssec, DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'dns0.eu official docs + community-verified addresses, dns0.eu (2026)',
  ),
  DnsEntry(
    id: 'dns0-open-v4',
    name: 'dns0.eu · Open (Unfiltered)',
    primary: '193.110.81.254',
    secondary: '185.253.5.254',
    country: 'EU',
    provider: 'dns0.eu',
    tags: {DnsTag.anycast, DnsTag.unfiltered},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'dns0.eu official docs + community-verified addresses, dns0.eu (2026)',
  ),
  DnsEntry(
    id: 'dns0-open-v6',
    name: 'dns0.eu · Open (Unfiltered) (IPv6)',
    primaryV6: '2a0f:fc80::ffff',
    secondaryV6: '2a0f:fc81::ffff',
    country: 'EU',
    provider: 'dns0.eu',
    tags: {DnsTag.anycast, DnsTag.unfiltered},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'dns0.eu official docs + community-verified addresses, dns0.eu (2026)',
  ),
  DnsEntry(
    id: 'dns0-open-doh',
    name: 'dns0.eu · Open (Unfiltered) (DoH)',
    dohUrl: 'https://open.dns0.eu/',
    country: 'EU',
    provider: 'dns0.eu',
    tags: {DnsTag.anycast, DnsTag.unfiltered},
    protocols: {DnsProtocol.doh},
    source: 'dns0.eu official docs + community-verified addresses, dns0.eu (2026)',
  ),
  DnsEntry(
    id: 'dns4eu-protective-v4',
    name: 'DNS4EU · Protective Resolution',
    primary: '86.54.11.1',
    secondary: '86.54.11.201',
    country: 'EU',
    provider: 'DNS4EU',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.security, DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'DNS4EU Public Service official docs, joindns4.eu/for-public (2026) — all 5 published resolver profiles',
  ),
  DnsEntry(
    id: 'dns4eu-protective-v6',
    name: 'DNS4EU · Protective Resolution (IPv6)',
    primaryV6: '2a13:1001::86:54:11:1',
    secondaryV6: '2a13:1001::86:54:11:201',
    country: 'EU',
    provider: 'DNS4EU',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.security, DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'DNS4EU Public Service official docs, joindns4.eu/for-public (2026) — all 5 published resolver profiles',
  ),
  DnsEntry(
    id: 'dns4eu-protective-doh',
    name: 'DNS4EU · Protective Resolution (DoH)',
    dohUrl: 'https://protective.joindns4.eu/dns-query',
    country: 'EU',
    provider: 'DNS4EU',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.security, DnsTag.geo},
    protocols: {DnsProtocol.doh},
    source: 'DNS4EU Public Service official docs, joindns4.eu/for-public (2026) — all 5 published resolver profiles',
  ),
  DnsEntry(
    id: 'dns4eu-protective-dot',
    name: 'DNS4EU · Protective Resolution (DoT)',
    dotHost: 'protective.joindns4.eu',
    country: 'EU',
    provider: 'DNS4EU',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.security, DnsTag.geo},
    protocols: {DnsProtocol.dot},
    source: 'DNS4EU Public Service official docs, joindns4.eu/for-public (2026) — all 5 published resolver profiles',
  ),
  DnsEntry(
    id: 'dns4eu-child-v4',
    name: 'DNS4EU · Protective + Child Protection',
    primary: '86.54.11.12',
    secondary: '86.54.11.212',
    country: 'EU',
    provider: 'DNS4EU',
    tags: {DnsTag.anycast, DnsTag.family, DnsTag.blocking, DnsTag.security, DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'DNS4EU Public Service official docs, joindns4.eu/for-public (2026) — all 5 published resolver profiles',
  ),
  DnsEntry(
    id: 'dns4eu-child-v6',
    name: 'DNS4EU · Protective + Child Protection (IPv6)',
    primaryV6: '2a13:1001::86:54:11:12',
    secondaryV6: '2a13:1001::86:54:11:212',
    country: 'EU',
    provider: 'DNS4EU',
    tags: {DnsTag.anycast, DnsTag.family, DnsTag.blocking, DnsTag.security, DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'DNS4EU Public Service official docs, joindns4.eu/for-public (2026) — all 5 published resolver profiles',
  ),
  DnsEntry(
    id: 'dns4eu-child-doh',
    name: 'DNS4EU · Protective + Child Protection (DoH)',
    dohUrl: 'https://child.joindns4.eu/dns-query',
    country: 'EU',
    provider: 'DNS4EU',
    tags: {DnsTag.anycast, DnsTag.family, DnsTag.blocking, DnsTag.security, DnsTag.geo},
    protocols: {DnsProtocol.doh},
    source: 'DNS4EU Public Service official docs, joindns4.eu/for-public (2026) — all 5 published resolver profiles',
  ),
  DnsEntry(
    id: 'dns4eu-child-dot',
    name: 'DNS4EU · Protective + Child Protection (DoT)',
    dotHost: 'child.joindns4.eu',
    country: 'EU',
    provider: 'DNS4EU',
    tags: {DnsTag.anycast, DnsTag.family, DnsTag.blocking, DnsTag.security, DnsTag.geo},
    protocols: {DnsProtocol.dot},
    source: 'DNS4EU Public Service official docs, joindns4.eu/for-public (2026) — all 5 published resolver profiles',
  ),
  DnsEntry(
    id: 'dns4eu-noads-v4',
    name: 'DNS4EU · Protective + Ad Blocking',
    primary: '86.54.11.13',
    secondary: '86.54.11.213',
    country: 'EU',
    provider: 'DNS4EU',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.security, DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'DNS4EU Public Service official docs, joindns4.eu/for-public (2026) — all 5 published resolver profiles',
  ),
  DnsEntry(
    id: 'dns4eu-noads-v6',
    name: 'DNS4EU · Protective + Ad Blocking (IPv6)',
    primaryV6: '2a13:1001::86:54:11:13',
    secondaryV6: '2a13:1001::86:54:11:213',
    country: 'EU',
    provider: 'DNS4EU',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.security, DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'DNS4EU Public Service official docs, joindns4.eu/for-public (2026) — all 5 published resolver profiles',
  ),
  DnsEntry(
    id: 'dns4eu-noads-doh',
    name: 'DNS4EU · Protective + Ad Blocking (DoH)',
    dohUrl: 'https://noads.joindns4.eu/dns-query',
    country: 'EU',
    provider: 'DNS4EU',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.security, DnsTag.geo},
    protocols: {DnsProtocol.doh},
    source: 'DNS4EU Public Service official docs, joindns4.eu/for-public (2026) — all 5 published resolver profiles',
  ),
  DnsEntry(
    id: 'dns4eu-noads-dot',
    name: 'DNS4EU · Protective + Ad Blocking (DoT)',
    dotHost: 'noads.joindns4.eu',
    country: 'EU',
    provider: 'DNS4EU',
    tags: {DnsTag.anycast, DnsTag.blocking, DnsTag.security, DnsTag.geo},
    protocols: {DnsProtocol.dot},
    source: 'DNS4EU Public Service official docs, joindns4.eu/for-public (2026) — all 5 published resolver profiles',
  ),
  DnsEntry(
    id: 'dns4eu-child-noads-v4',
    name: 'DNS4EU · Protective + Child + Ad Blocking',
    primary: '86.54.11.11',
    secondary: '86.54.11.211',
    country: 'EU',
    provider: 'DNS4EU',
    tags: {DnsTag.anycast, DnsTag.family, DnsTag.blocking, DnsTag.security, DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'DNS4EU Public Service official docs, joindns4.eu/for-public (2026) — all 5 published resolver profiles',
  ),
  DnsEntry(
    id: 'dns4eu-child-noads-v6',
    name: 'DNS4EU · Protective + Child + Ad Blocking (IPv6)',
    primaryV6: '2a13:1001::86:54:11:11',
    secondaryV6: '2a13:1001::86:54:11:211',
    country: 'EU',
    provider: 'DNS4EU',
    tags: {DnsTag.anycast, DnsTag.family, DnsTag.blocking, DnsTag.security, DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'DNS4EU Public Service official docs, joindns4.eu/for-public (2026) — all 5 published resolver profiles',
  ),
  DnsEntry(
    id: 'dns4eu-child-noads-doh',
    name: 'DNS4EU · Protective + Child + Ad Blocking (DoH)',
    dohUrl: 'https://child-noads.joindns4.eu/dns-query',
    country: 'EU',
    provider: 'DNS4EU',
    tags: {DnsTag.anycast, DnsTag.family, DnsTag.blocking, DnsTag.security, DnsTag.geo},
    protocols: {DnsProtocol.doh},
    source: 'DNS4EU Public Service official docs, joindns4.eu/for-public (2026) — all 5 published resolver profiles',
  ),
  DnsEntry(
    id: 'dns4eu-child-noads-dot',
    name: 'DNS4EU · Protective + Child + Ad Blocking (DoT)',
    dotHost: 'child-noads.joindns4.eu',
    country: 'EU',
    provider: 'DNS4EU',
    tags: {DnsTag.anycast, DnsTag.family, DnsTag.blocking, DnsTag.security, DnsTag.geo},
    protocols: {DnsProtocol.dot},
    source: 'DNS4EU Public Service official docs, joindns4.eu/for-public (2026) — all 5 published resolver profiles',
  ),
  DnsEntry(
    id: 'dns4eu-unfiltered-v4',
    name: 'DNS4EU · Unfiltered Resolution',
    primary: '86.54.11.100',
    secondary: '86.54.11.200',
    country: 'EU',
    provider: 'DNS4EU',
    tags: {DnsTag.anycast, DnsTag.unfiltered, DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'DNS4EU Public Service official docs, joindns4.eu/for-public (2026) — all 5 published resolver profiles',
  ),
  DnsEntry(
    id: 'dns4eu-unfiltered-v6',
    name: 'DNS4EU · Unfiltered Resolution (IPv6)',
    primaryV6: '2a13:1001::86:54:11:100',
    secondaryV6: '2a13:1001::86:54:11:200',
    country: 'EU',
    provider: 'DNS4EU',
    tags: {DnsTag.anycast, DnsTag.unfiltered, DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'DNS4EU Public Service official docs, joindns4.eu/for-public (2026) — all 5 published resolver profiles',
  ),
  DnsEntry(
    id: 'dns4eu-unfiltered-doh',
    name: 'DNS4EU · Unfiltered Resolution (DoH)',
    dohUrl: 'https://unfiltered.joindns4.eu/dns-query',
    country: 'EU',
    provider: 'DNS4EU',
    tags: {DnsTag.anycast, DnsTag.unfiltered, DnsTag.geo},
    protocols: {DnsProtocol.doh},
    source: 'DNS4EU Public Service official docs, joindns4.eu/for-public (2026) — all 5 published resolver profiles',
  ),
  DnsEntry(
    id: 'dns4eu-unfiltered-dot',
    name: 'DNS4EU · Unfiltered Resolution (DoT)',
    dotHost: 'unfiltered.joindns4.eu',
    country: 'EU',
    provider: 'DNS4EU',
    tags: {DnsTag.anycast, DnsTag.unfiltered, DnsTag.geo},
    protocols: {DnsProtocol.dot},
    source: 'DNS4EU Public Service official docs, joindns4.eu/for-public (2026) — all 5 published resolver profiles',
  ),
  DnsEntry(
    id: 'dns-watch-v4',
    name: 'DNS.WATCH',
    primary: '84.200.69.80',
    secondary: '84.200.70.40',
    country: 'DE',
    provider: 'DNS.WATCH',
    tags: {DnsTag.unfiltered, DnsTag.dnssec, DnsTag.privacy},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'DNS.WATCH official docs, dns.watch (long-standing, stable)',
  ),
  DnsEntry(
    id: 'dns-watch-v6',
    name: 'DNS.WATCH (IPv6)',
    primaryV6: '2001:1608:10:25::1c04:b12f',
    country: 'DE',
    provider: 'DNS.WATCH',
    tags: {DnsTag.unfiltered, DnsTag.dnssec, DnsTag.privacy},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'DNS.WATCH official docs, dns.watch (long-standing, stable)',
  ),
  DnsEntry(
    id: 'fdn-v4',
    name: 'FDN (French Data Network, non-profit)',
    primary: '80.67.169.12',
    secondary: '80.67.169.40',
    country: 'FR',
    provider: 'FDN',
    tags: {DnsTag.unfiltered, DnsTag.nonprofit},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'French Data Network (FDN) non-profit resolver, fdn.fr/actions/dns (long-standing)',
  ),
  DnsEntry(
    id: 'fdn-v6',
    name: 'FDN (French Data Network, non-profit) (IPv6)',
    primaryV6: '2001:910:800::12',
    secondaryV6: '2001:910:800::40',
    country: 'FR',
    provider: 'FDN',
    tags: {DnsTag.unfiltered, DnsTag.nonprofit},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'French Data Network (FDN) non-profit resolver, fdn.fr/actions/dns (long-standing)',
  ),
  DnsEntry(
    id: 'libredns-doh',
    name: 'LibreDNS (DoH)',
    dohUrl: 'https://doh.libredns.gr/dns-query',
    country: 'GR',
    provider: 'LibreDNS',
    tags: {DnsTag.unfiltered, DnsTag.privacy},
    protocols: {DnsProtocol.doh},
    source: 'LibreDNS privacy resolver docs, libredns.gr',
  ),
  DnsEntry(
    id: 'mullvad-default-doh',
    name: 'Mullvad DNS · Default (DoH)',
    dohUrl: 'https://dns.mullvad.net/dns-query',
    country: 'SE',
    provider: 'Mullvad',
    tags: {DnsTag.privacy, DnsTag.unfiltered},
    protocols: {DnsProtocol.doh},
    source: 'Mullvad DNS official docs, mullvad.net/en/help/dns-over-https-and-dns-over-tls',
  ),
  DnsEntry(
    id: 'mullvad-adblock-doh',
    name: 'Mullvad DNS · Ad Block (DoH)',
    dohUrl: 'https://adblock.dns.mullvad.net/dns-query',
    country: 'SE',
    provider: 'Mullvad',
    tags: {DnsTag.privacy, DnsTag.blocking},
    protocols: {DnsProtocol.doh},
    source: 'Mullvad DNS official docs, mullvad.net/en/help/dns-over-https-and-dns-over-tls',
  ),
  DnsEntry(
    id: 'dnssb-v4',
    name: 'DNS.SB',
    primary: '185.222.222.222',
    secondary: '45.11.45.11',
    country: 'DE',
    provider: 'DNS.SB (xTom)',
    tags: {DnsTag.anycast, DnsTag.unfiltered, DnsTag.dnssec, DnsTag.privacy},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'DNS.SB official docs, dns.sb/guide + dns.sb/faq (Germany, 2026)',
  ),
  DnsEntry(
    id: 'dnssb-v6',
    name: 'DNS.SB (IPv6)',
    primaryV6: '2a09::',
    secondaryV6: '2a11::',
    country: 'DE',
    provider: 'DNS.SB (xTom)',
    tags: {DnsTag.anycast, DnsTag.unfiltered, DnsTag.dnssec, DnsTag.privacy},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'DNS.SB official docs, dns.sb/guide + dns.sb/faq (Germany, 2026)',
  ),
  DnsEntry(
    id: 'dnssb-doh',
    name: 'DNS.SB (DoH)',
    dohUrl: 'https://doh.dns.sb/dns-query',
    country: 'DE',
    provider: 'DNS.SB (xTom)',
    tags: {DnsTag.anycast, DnsTag.unfiltered, DnsTag.dnssec, DnsTag.privacy},
    protocols: {DnsProtocol.doh},
    source: 'DNS.SB official docs, dns.sb/guide + dns.sb/faq (Germany, 2026)',
  ),
  DnsEntry(
    id: 'dnssb-dot',
    name: 'DNS.SB (DoT)',
    dotHost: 'dot.sb',
    country: 'DE',
    provider: 'DNS.SB (xTom)',
    tags: {DnsTag.anycast, DnsTag.unfiltered, DnsTag.dnssec, DnsTag.privacy},
    protocols: {DnsProtocol.dot},
    source: 'DNS.SB official docs, dns.sb/guide + dns.sb/faq (Germany, 2026)',
  ),
  DnsEntry(
    id: 'ffmuc-v4',
    name: 'FFMUC (Freifunk München, non-profit)',
    primary: '5.1.66.255',
    secondary: '185.150.99.255',
    country: 'DE',
    provider: 'Freifunk München',
    tags: {DnsTag.unfiltered, DnsTag.nonprofit, DnsTag.dnssec, DnsTag.privacy},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Freifunk München (FFMUC) official docs, dns-setup.ffmuc.net (non-profit, DE/AT, 2026)',
  ),
  DnsEntry(
    id: 'ffmuc-v6',
    name: 'FFMUC (Freifunk München, non-profit) (IPv6)',
    primaryV6: '2001:678:e68:f000::',
    secondaryV6: '2001:678:ed0:f000::',
    country: 'DE',
    provider: 'Freifunk München',
    tags: {DnsTag.unfiltered, DnsTag.nonprofit, DnsTag.dnssec, DnsTag.privacy},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Freifunk München (FFMUC) official docs, dns-setup.ffmuc.net (non-profit, DE/AT, 2026)',
  ),
  DnsEntry(
    id: 'ffmuc-doh',
    name: 'FFMUC (Freifunk München, non-profit) (DoH)',
    dohUrl: 'https://doh.ffmuc.net/dns-query',
    country: 'DE',
    provider: 'Freifunk München',
    tags: {DnsTag.unfiltered, DnsTag.nonprofit, DnsTag.dnssec, DnsTag.privacy},
    protocols: {DnsProtocol.doh},
    source: 'Freifunk München (FFMUC) official docs, dns-setup.ffmuc.net (non-profit, DE/AT, 2026)',
  ),
  DnsEntry(
    id: 'ffmuc-dot',
    name: 'FFMUC (Freifunk München, non-profit) (DoT)',
    dotHost: 'dot.ffmuc.net',
    country: 'DE',
    provider: 'Freifunk München',
    tags: {DnsTag.unfiltered, DnsTag.nonprofit, DnsTag.dnssec, DnsTag.privacy},
    protocols: {DnsProtocol.dot},
    source: 'Freifunk München (FFMUC) official docs, dns-setup.ffmuc.net (non-profit, DE/AT, 2026)',
  ),
  DnsEntry(
    id: 'dnsforge-v4',
    name: 'dnsforge.de',
    primary: '176.9.93.198',
    secondary: '176.9.1.117',
    country: 'DE',
    provider: 'dnsforge.de',
    tags: {DnsTag.blocking, DnsTag.privacy},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'dnsforge.de current config, verified via community write-up (Germany, non-profit-run)',
  ),
  DnsEntry(
    id: 'dnsforge-v6',
    name: 'dnsforge.de (IPv6)',
    primaryV6: '2a01:4f8:151:34aa::198',
    secondaryV6: '2a01:4f8:141:316d::117',
    country: 'DE',
    provider: 'dnsforge.de',
    tags: {DnsTag.blocking, DnsTag.privacy},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'dnsforge.de current config, verified via community write-up (Germany, non-profit-run)',
  ),
  DnsEntry(
    id: 'dnsforge-dot',
    name: 'dnsforge.de (DoT)',
    dotHost: 'dnsforge.de',
    country: 'DE',
    provider: 'dnsforge.de',
    tags: {DnsTag.blocking, DnsTag.privacy},
    protocols: {DnsProtocol.dot},
    source: 'dnsforge.de current config, verified via community write-up (Germany, non-profit-run)',
  ),
  DnsEntry(
    id: 'digitale-gesellschaft-v4',
    name: 'Digitale Gesellschaft (Switzerland, non-profit)',
    primary: '185.95.218.42',
    secondary: '185.95.218.43',
    country: 'CH',
    provider: 'Digitale Gesellschaft',
    tags: {DnsTag.unfiltered, DnsTag.nonprofit, DnsTag.dnssec, DnsTag.privacy},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Digitale Gesellschaft (Switzerland) official docs, github.com/DigitaleGesellschaft/DNS-Resolver',
  ),
  DnsEntry(
    id: 'digitale-gesellschaft-v6',
    name: 'Digitale Gesellschaft (Switzerland, non-profit) (IPv6)',
    primaryV6: '2a05:fc84::42',
    secondaryV6: '2a05:fc84::43',
    country: 'CH',
    provider: 'Digitale Gesellschaft',
    tags: {DnsTag.unfiltered, DnsTag.nonprofit, DnsTag.dnssec, DnsTag.privacy},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Digitale Gesellschaft (Switzerland) official docs, github.com/DigitaleGesellschaft/DNS-Resolver',
  ),
  DnsEntry(
    id: 'digitale-gesellschaft-doh',
    name: 'Digitale Gesellschaft (Switzerland, non-profit) (DoH)',
    dohUrl: 'https://dns.digitale-gesellschaft.ch/dns-query',
    country: 'CH',
    provider: 'Digitale Gesellschaft',
    tags: {DnsTag.unfiltered, DnsTag.nonprofit, DnsTag.dnssec, DnsTag.privacy},
    protocols: {DnsProtocol.doh},
    source: 'Digitale Gesellschaft (Switzerland) official docs, github.com/DigitaleGesellschaft/DNS-Resolver',
  ),
  DnsEntry(
    id: 'digitale-gesellschaft-dot',
    name: 'Digitale Gesellschaft (Switzerland, non-profit) (DoT)',
    dotHost: 'dns.digitale-gesellschaft.ch',
    country: 'CH',
    provider: 'Digitale Gesellschaft',
    tags: {DnsTag.unfiltered, DnsTag.nonprofit, DnsTag.dnssec, DnsTag.privacy},
    protocols: {DnsProtocol.dot},
    source: 'Digitale Gesellschaft (Switzerland) official docs, github.com/DigitaleGesellschaft/DNS-Resolver',
  ),
  DnsEntry(
    id: 'digitalcourage-dot',
    name: 'Digitalcourage (Germany, non-profit, DoT-only) (DoT)',
    dotHost: 'dns3.digitalcourage.de',
    country: 'DE',
    provider: 'Digitalcourage',
    tags: {DnsTag.unfiltered, DnsTag.nonprofit, DnsTag.privacy},
    protocols: {DnsProtocol.dot},
    source: 'Digitalcourage e.V. official DoT resolver, dns3.digitalcourage.de (Germany, non-profit; DoT only, no plain-DNS IP published)',
  ),
];
