// app/lib/services/dns_directory_ir.dart
//
// Iran-focused directory, ported 1:1 from the app's existing
// game_dns.dart (kGameDnsList) into the new DnsEntry model. These are
// NOT newly sourced — they were already shipping and user-tested;
// this file only re-shapes them, addresses are unchanged.

import '../models/dns_entry.dart';

// Iran
final List<DnsEntry> kIrDnsDirectory = <DnsEntry>[
  DnsEntry(
    id: 'ir-electro-v4',
    name: '🎮 Electro',
    primary: '78.157.42.100',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Electro',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-electro-2-v4',
    name: '🎮 Electro 2',
    primary: '78.157.42.101',
    secondary: '78.157.42.100',
    country: 'IR',
    provider: 'Electro',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-403online-v4',
    name: '🎮 403 Online',
    primary: '10.202.10.202',
    secondary: '10.202.10.102',
    country: 'IR',
    provider: '403 Online',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-radar-v4',
    name: '🎮 Radar Game',
    primary: '10.202.10.10',
    secondary: '10.202.10.11',
    country: 'IR',
    provider: 'Radar',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-shecan-gaming-v4',
    name: '🎮 Shecan Gaming',
    primary: '185.51.200.2',
    secondary: '178.22.122.100',
    country: 'IR',
    provider: 'Shecan',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-begzar-v4',
    name: '🎮 Begzar',
    primary: '185.55.226.26',
    secondary: '185.55.225.25',
    country: 'IR',
    provider: 'Begzar',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-1-v4',
    name: '🇮🇷 ایران ۱',
    primary: '37.32.5.61',
    secondary: '37.32.5.60',
    country: 'IR',
    provider: 'Iran',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-2-v4',
    name: '🇮🇷 ایران ۲',
    primary: '10.139.177.22',
    secondary: '10.139.177.21',
    country: 'IR',
    provider: 'Iran',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-3-v4',
    name: '🇮🇷 ایران ۳',
    primary: '94.103.125.158',
    secondary: '94.103.125.157',
    country: 'IR',
    provider: 'Iran',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-4-v4',
    name: '🇮🇷 ایران ۴',
    primary: '10.202.10.11',
    secondary: '10.202.10.10',
    country: 'IR',
    provider: 'Iran',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-5-v4',
    name: '🇮🇷 ایران ۵',
    primary: '31.192.108.180',
    secondary: '31.192.108.181',
    country: 'IR',
    provider: 'Iran',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-6-v4',
    name: '🇮🇷 ایران ۶',
    primary: '31.129.110.240',
    secondary: '45.90.33.120',
    country: 'IR',
    provider: 'Iran',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-7-v4',
    name: '🇮🇷 ایران ۷',
    primary: '185.55.225.25',
    secondary: '185.55.226.26',
    country: 'IR',
    provider: 'Iran',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-8-v4',
    name: '🇮🇷 ایران ۸',
    primary: '111.88.96.50',
    secondary: '111.88.96.51',
    country: 'IR',
    provider: 'Iran',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-9-v4',
    name: '🇮🇷 ایران ۹ (همراه اول)',
    primary: '178.22.122.100',
    secondary: '185.40.202.5',
    country: 'IR',
    provider: 'Hamrah-e Avval',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-10-v4',
    name: '🇮🇷 ایران ۱۰ (ایرانسل)',
    primary: '178.22.122.100',
    secondary: '185.51.200.2',
    country: 'IR',
    provider: 'Irancell',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-11-v4',
    name: '🇮🇷 ایران ۱۱ (مناطق خاص)',
    primary: '178.22.122.100',
    secondary: '48.83.124.16',
    country: 'IR',
    provider: 'Iran',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-shecan-v4',
    name: '🌐 Shecan',
    primary: '78.157.42.100',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Shecan',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-shecan-v2-v4',
    name: '🌐 Shecan v2',
    primary: '78.157.32.100',
    secondary: '1.1.1.1',
    country: 'IR',
    provider: 'Shecan',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-7676-v4',
    name: '🌐 76.76 A',
    primary: '76.76.2.22',
    secondary: '76.76.10.22',
    country: 'IR',
    provider: 'Misc',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-132132-v4',
    name: '🌐 132.132',
    primary: '132.132.7.7',
    secondary: '78.157.32.202',
    country: 'IR',
    provider: 'Misc',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-4590-v4',
    name: '🌐 45.90',
    primary: '45.90.33.120',
    secondary: '45.90.126.10',
    country: 'IR',
    provider: 'Misc',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-cf-v4',
    name: '☁ Cloudflare',
    primary: '1.1.1.1',
    secondary: '1.0.0.1',
    country: 'IR',
    provider: 'Cloudflare',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-cf-od-v4',
    name: '☁ Cloudflare+OpenDNS',
    primary: '1.1.1.1',
    secondary: '208.67.222.222',
    country: 'IR',
    provider: 'Mixed',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-od-v4',
    name: '🟠 OpenDNS',
    primary: '208.67.220.220',
    secondary: '129.250.35.20',
    country: 'IR',
    provider: 'OpenDNS',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-od-2-v4',
    name: '🟠 OpenDNS 2',
    primary: '185.106.54.225',
    secondary: '209.244.0.3',
    country: 'IR',
    provider: 'OpenDNS',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-level3-v4',
    name: '🔵 Level3',
    primary: '209.244.0.3',
    secondary: '209.244.0.4',
    country: 'IR',
    provider: 'Level3',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-adguard-v4',
    name: '🛡 AdGuard',
    primary: '94.103.125.158',
    secondary: '94.103.125.157',
    country: 'IR',
    provider: 'AdGuard',
    tags: {DnsTag.geo, DnsTag.blocking},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-adguard-2-v4',
    name: '🛡 AdGuard 2',
    primary: '176.97.78.78',
    secondary: '1.1.1.1',
    country: 'IR',
    provider: 'AdGuard',
    tags: {DnsTag.geo, DnsTag.blocking},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-4590-a-v4',
    name: '🟢 45.90 - A',
    primary: '45.90.30.190',
    secondary: '45.90.28.190',
    country: 'IR',
    provider: 'Misc',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-4590-b-v4',
    name: '🟢 45.90 - B',
    primary: '45.90.28.190',
    secondary: '45.90.30.190',
    country: 'IR',
    provider: 'Misc',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-4590-c-v4',
    name: '🟢 45.90 - C',
    primary: '185.51.200.2',
    secondary: '45.90.28.0',
    country: 'IR',
    provider: 'Misc',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-155-v4',
    name: '🎮 Game 50.155',
    primary: '50.155.77.121',
    secondary: '1.1.1.1',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-57-v4',
    name: '🎮 Game 50.57',
    primary: '50.57.126.32',
    secondary: '1.1.1.1',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-43-v4',
    name: '🎮 Game 50.43',
    primary: '50.43.66.162',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-229-v4',
    name: '🎮 Game 50.229',
    primary: '50.229.158.27',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-194-v4',
    name: '🎮 Game 50.194',
    primary: '50.194.26.120',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-233-v4',
    name: '🎮 Game 50.233',
    primary: '50.233.133.248',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-137-v4',
    name: '🎮 Game 50.137',
    primary: '50.137.149.238',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-72-v4',
    name: '🎮 Game 50.72',
    primary: '50.72.132.158',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-3-v4',
    name: '🎮 Game 50.3',
    primary: '50.3.121.54',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-214-v4',
    name: '🎮 Game 50.214',
    primary: '50.214.62.98',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-21-v4',
    name: '🎮 Game 50.21',
    primary: '50.21.23.88',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-198-v4',
    name: '🎮 Game 50.198',
    primary: '50.198.128.213',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-89-v4',
    name: '🎮 Game 50.89',
    primary: '50.89.102.61',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-101-v4',
    name: '🎮 Game 50.101',
    primary: '50.101.247.89',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-70-v4',
    name: '🎮 Game 50.70',
    primary: '50.70.97.119',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-123-v4',
    name: '🎮 Game 50.123',
    primary: '50.123.63.237',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-97-v4',
    name: '🎮 Game 50.97',
    primary: '50.97.223.66',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-108-v4',
    name: '🎮 Game 50.108',
    primary: '50.108.5.223',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-1-v4',
    name: '🎮 Game 50.1',
    primary: '50.1.79.33',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-15-v4',
    name: '🎮 Game 50.15',
    primary: '50.15.111.249',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-213-v4',
    name: '🎮 Game 50.213',
    primary: '50.213.155.206',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-68-v4',
    name: '🎮 Game 50.68',
    primary: '50.68.118.111',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-113-v4',
    name: '🎮 Game 50.113',
    primary: '50.113.227.119',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-12-v4',
    name: '🎮 Game 50.12',
    primary: '50.12.148.236',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-50-v4',
    name: '🎮 Game 50.50',
    primary: '50.50.5.58',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-131-v4',
    name: '🎮 Game 50.131',
    primary: '50.131.141.140',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-31-v4',
    name: '🎮 Game 50.31',
    primary: '50.31.48.158',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-200-v4',
    name: '🎮 Game 50.200',
    primary: '50.200.96.227',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-45-v4',
    name: '🎮 Game 50.45',
    primary: '50.45.159.244',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-230-v4',
    name: '🎮 Game 50.230',
    primary: '50.230.79.142',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-53-v4',
    name: '🎮 Game 50.53',
    primary: '50.53.62.4',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-36-v4',
    name: '🎮 Game 50.36',
    primary: '50.36.165.208',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-174-v4',
    name: '🎮 Game 50.174',
    primary: '50.174.101.218',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-62-v4',
    name: '🎮 Game 50.62',
    primary: '78.157.42.101',
    secondary: '50.62.185.5',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-0-v4',
    name: '🎮 Game 50.0',
    primary: '78.157.42.101',
    secondary: '50.0.212.76',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-50-227-v4',
    name: '🎮 Game 50.227',
    primary: '78.157.42.101',
    secondary: '50.227.104.49',
    country: 'IR',
    provider: 'Gaming',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-doh-zdnro-doh',
    name: '🔒 DoH zdn.ro (DoH)',
    dohUrl: 'https://zdn.ro/dns-query',
    country: 'IR',
    provider: 'Misc',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.doh},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-doh-ada-doh',
    name: '🔒 DoH ada (DoH)',
    dohUrl: 'https://ada.openbld.net/dns-query',
    country: 'IR',
    provider: 'Misc',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.doh},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-doh-cfgw-doh',
    name: '🔒 DoH Cloudflare GW (DoH)',
    dohUrl: 'https://frd4wvnobp.cloudflare-gateway.com/dns-query',
    country: 'IR',
    provider: 'Cloudflare',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.doh},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-doh-l337-doh',
    name: '🔒 DoH l337.site (DoH)',
    dohUrl: 'https://dns.l337.site/dns-query',
    country: 'IR',
    provider: 'Misc',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.doh},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-doh-anon-doh',
    name: '🔒 DoH dns.anon.no (DoH)',
    dohUrl: 'https://dns.anon.no/dns-query',
    country: 'IR',
    provider: 'Misc',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.doh},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-de-v4v6-v4',
    name: '🇩🇪 Germany v4+v6',
    primary: '78.157.42.100',
    secondary: '91.108.145.18',
    country: 'DE',
    provider: 'Misc',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-de-v4v6-v6',
    name: '🇩🇪 Germany v4+v6 (IPv6)',
    primaryV6: '2001:4fef:80ff::b2d1',
    secondaryV6: '2001:d534:3fa5::adfd',
    country: 'DE',
    provider: 'Misc',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-v6-a-v4',
    name: '🔵 IPv6 Set A',
    primary: '1.1.1.1',
    secondary: '1.0.0.1',
    country: 'IR',
    provider: 'Misc',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-v6-a-v6',
    name: '🔵 IPv6 Set A (IPv6)',
    primaryV6: '5e56:a508:873b:1e6d:5936:14de:c799:e24a',
    secondaryV6: 'cb1c:2deb:28ed:d339:3bbe:1665:81df:4938',
    country: 'IR',
    provider: 'Misc',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-v6-b-v4',
    name: '🔵 IPv6 Set B',
    primary: '78.157.42.100',
    secondary: '78.157.42.101',
    country: 'IR',
    provider: 'Misc',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-v6-b-v6',
    name: '🔵 IPv6 Set B (IPv6)',
    primaryV6: '2001:4fef:80ff::b2d1',
    secondaryV6: '2001:d534:3fa5::adfd',
    country: 'IR',
    provider: 'Misc',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-dnscrypt-adguard-v4',
    name: '🔐 AdGuard DNSCrypt',
    primary: '94.140.14.14',
    secondary: '94.140.15.15',
    country: 'IR',
    provider: 'AdGuard',
    tags: {DnsTag.geo, DnsTag.blocking},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-dnscrypt-adguard-family-v4',
    name: '🔐 AdGuard Family',
    primary: '94.140.14.15',
    secondary: '94.140.15.16',
    country: 'IR',
    provider: 'AdGuard',
    tags: {DnsTag.geo, DnsTag.family, DnsTag.blocking},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-dnscrypt-adguard-unfiltered-v4',
    name: '🔐 AdGuard Unfiltered',
    primary: '94.140.14.140',
    secondary: '94.140.14.141',
    country: 'IR',
    provider: 'AdGuard',
    tags: {DnsTag.geo, DnsTag.unfiltered},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-dnscrypt-quad9-v4',
    name: '🔐 Quad9 DNSCrypt',
    primary: '9.9.9.9',
    secondary: '149.112.112.112',
    country: 'IR',
    provider: 'Quad9',
    tags: {DnsTag.geo, DnsTag.blocking},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-dnscrypt-cf-v4',
    name: '🔐 Cloudflare DNSCrypt',
    primary: '1.1.1.1',
    secondary: '1.0.0.1',
    country: 'IR',
    provider: 'Cloudflare',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-adfilter-adelaide-v4',
    name: '🔐 ADFilter Adelaide',
    primary: '103.249.238.124',
    secondary: '203.29.241.76',
    country: 'AU',
    provider: 'ADFilter',
    tags: {DnsTag.blocking},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-adfilter-perth-v4',
    name: '🔐 ADFilter Perth',
    primary: '203.29.241.76',
    secondary: '112.213.32.219',
    country: 'AU',
    provider: 'ADFilter',
    tags: {DnsTag.blocking},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-adfilter-sydney-v4',
    name: '🔐 ADFilter Sydney',
    primary: '112.213.32.219',
    secondary: '103.249.238.124',
    country: 'AU',
    provider: 'ADFilter',
    tags: {DnsTag.blocking},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-dnscrypt-geneva-v4',
    name: '🔐 dnscry.pt Geneva',
    primary: '194.135.119.158',
    secondary: '194.135.119.158',
    country: 'CH',
    provider: 'dnscry.pt',
    tags: <DnsTag>{},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-cryptostorm-bg-v4',
    name: '🔐 Cryptostorm Bulgaria',
    primary: '37.120.152.235',
    secondary: '37.120.152.235',
    country: 'BG',
    provider: 'Cryptostorm',
    tags: <DnsTag>{},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-19236-v4',
    name: '⚡ 1.92.36',
    primary: '1.92.36.131',
    secondary: '78.157.42.100',
    country: 'IR',
    provider: 'Misc',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-6521-v4',
    name: '⚡ 65.21',
    primary: '65.21.242.77',
    secondary: '78.157.42.100',
    country: 'IR',
    provider: 'Misc',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-7815742100-v4',
    name: '⚡ 78.157.42.100 set',
    primary: '78.157.42.100',
    secondary: '8.119.51.48',
    country: 'IR',
    provider: 'Misc',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
  DnsEntry(
    id: 'ir-cf-10183-v4',
    name: '⚡ 1.1.1.1 + 10.183',
    primary: '1.1.1.1',
    secondary: '10.183.213.29',
    country: 'IR',
    provider: 'Mixed',
    tags: {DnsTag.geo},
    protocols: {DnsProtocol.udp, DnsProtocol.tcp},
    source: 'Ported from the app\'s existing game_dns.dart (kGameDnsList), already in production use and user-verified against Iranian networks',
  ),
];
