/// لیست SNIهای پیش‌فرض برای پل‌های Tor (obfs4/snowflake/meek/webtunnel).
/// این SNIها باعث می‌شوند ترافیک Tor شبیه یک سایت معتبر یا داخلی
/// به‌نظر برسد و DPI آن را مسدود نکند.
class TorSniPresets {
  TorSniPresets._();

  /// SNIهای عمومی معروف.
  static const List<String> generic = <String>[
    'certum.pl',
    'letsencrypt.org',
    'sourceforge.net',
    'google.com',
    'scholar.google.com',
    'news.google.com',
    'mail.google.com',
    'support.google.com',
    'search.google.com',
    'site.google.com',
    'sheets.google.com',
    'email.google.com',
    'supermario.corp.google.com',
    'actualities.google.com',
    'chatgpt.com',
    'openai.com',
    'gitlab.com',
    'vercel.com',
    'vercel.app',
    'atlassian.com',
    'okta.com',
    'epicgames.com',
    'chess.com',
    'react.dev',
    'python.org',
    'ubuntu.com',
    'centos.org',
    'cdnjs.com',
    'cdn77.com',
    'gold-team.org',
    'rio.ggusers.com',
    'gifpey.info',
    'nairobi.saymyname.website',
    'berlin.saymyname.website',
    'myf2mi.top',
    'f2me.top',
    '8.6.112.0.sslip.io',
    '2.188.21.46.sslip.io',
    '162.159.152.4.sslip.io',
    '2.188.21.130.sslip.io',
    '87.107.110.155.sslip.io',
  ];

  /// دامنه‌های ایرانی که DPI داخلی با آن‌ها راحت‌تر است.
  static const List<String> iranian = <String>[
    'neshan.org',
    'subkade.ir',
    'shaadbin.ir',
    'uupload.ir',
    'gerdoo.me',
    'bazion.ir',
    'abadis.ir',
    'ikac.ir',
    'ebooksworld.ir',
    'iranicard.ir',
    'gameq.ir',
    'melovaz.ir',
    'uploadboy.com',
    'soft98.ir',
    'daneshpaz.top',
    'uploadina.com',
    'sarzamindownload.com',
    'asiatech.ir',
    'shecan.ir',
    'par30games.net',
    '3fa.ir',
    'taaghche.com',
    'downloadly.ir',
    'oldtowns.top',
    'cafebazaar.ir',
    'shaparak.ir',
    'uploadkon.ir',
    'varzesh3.com',
    'downloadha.com',
    'filimo.com',
    'search.bertina.ir',
    'chat.boofai.com',
    'farsroid.com',
    'bosgame.ir',
    'divar.ir',
    'snap.ir',
    'nic.ir',
    'flzios.ir',
    'digikala.com',
    'fastdic.com',
    'aparat.com',
    'download.ir',
    'yasdl.com',
    'pastehub.ir',
    'iranmatlab.ir',
    'bitpin.ir',
    'my.files.ir',
    'post.ir',
    'picofile.com',
    'namnak.com',
    'gov.ir',
    'nixfile.com',
    'pirategames.ir',
    'balad.ir',
    'faraazin.ir',
    'vgdl.ir',
    'aharvesal.ir',
    'chat.smartbytes.ir',
    'behmelody.in',
    'cup.theazizi.ir',
    'alibaba.ir',
    'zarebin.ir',
    'patoghu.com',
    'subzone.ir',
    'navaar.ir',
    'zoomit.ir',
    'linklick.ir',
    'dlfox.com',
    'fidibo.com',
    'tamin.ir',
    'guardnet.ir',
    'irimo.ir',
    'm.ulni.ir',
    'myket.ir',
    'telewebion.com',
    'airport.ir',
    'radio.9craft.ir',
    'torob.com',
    'rubika.ir',
    'mizanonline.ir',
    'gapgpt.app',
    'ninisite.com',
    'hooshyar.golrang.ai',
    'hooshang.ai',
    'libra-books.com',
    'dl2.sermoviedown.pw',
    'dls2.iran-gamecenter-host.com',
    'dic.b-amooz.com',
  ];

  /// همه‌ی SNIها (ترکیب generic و iranian).
  static List<String> get all => <String>[...generic, ...iranian];

  /// SNI پیش‌فرض
  static const String defaultSni = 'certum.pl';
}
