#!/usr/bin/env python3
"""
تولید فایل محافظت‌شدهٔ اشتراک‌های پیش‌فرض (فقط در CI اجرا می‌شود).

ورودی : متغیر محیطی DEFAULT_SUBS_JSON  (از GitHub Secret)
         [{"id": "spider", "name": "🕷 Spider", "url": "https://..."}, ...]
خروجی : مسیر داده‌شده در آرگومان اول (protected_defaults.g.dart)

لینک‌ها هیچ‌وقت داخل ریپو یا سورس نمی‌آیند؛ فقط به شکل رمزشده در APK می‌روند.
رمز: HMAC-SHA256 در حالت CTR + برچسب صحت (encrypt-then-MAC).
کلید هر بیلد تصادفی است و به ۴ تکه شکسته می‌شود.
"""
import base64
import hashlib
import hmac
import json
import os
import sys


def keystream_block(key: bytes, nonce: bytes, counter: int) -> bytes:
    return hmac.new(key, b"enc" + nonce + counter.to_bytes(4, "big"), hashlib.sha256).digest()


def encrypt(key: bytes, plaintext: bytes) -> bytes:
    nonce = os.urandom(12)
    ct = bytearray()
    for i in range(0, len(plaintext), 32):
        ks = keystream_block(key, nonce, i // 32)
        chunk = plaintext[i:i + 32]
        ct.extend(b ^ k for b, k in zip(chunk, ks))
    tag = hmac.new(key, b"mac" + nonce + bytes(ct), hashlib.sha256).digest()[:16]
    return nonce + bytes(ct) + tag


def decrypt(key: bytes, blob: bytes) -> bytes:
    """فقط برای تست؛ همان الگوریتم پیاده‌شده در Dart."""
    nonce, ct, tag = blob[:12], blob[12:-16], blob[-16:]
    mac = hmac.new(key, b"mac" + nonce + ct, hashlib.sha256).digest()[:16]
    if not hmac.compare_digest(mac, tag):
        raise ValueError("bad tag")
    out = bytearray()
    for i in range(0, len(ct), 32):
        ks = keystream_block(key, nonce, i // 32)
        out.extend(b ^ k for b, k in zip(ct[i:i + 32], ks))
    return bytes(out)


def split_key(key: bytes, parts: int = 4):
    shares = [os.urandom(len(key)) for _ in range(parts - 1)]
    last = bytearray(key)
    for s in shares:
        last = bytearray(a ^ b for a, b in zip(last, s))
    shares.append(bytes(last))
    return shares


def dart_str(s: str) -> str:
    s = (s.replace("\\", "\\\\").replace("'", "\\'")
          .replace("$", "\\$").replace("\n", "\\n").replace("\r", ""))
    return "'" + s + "'"


def dart_bytes(b: bytes) -> str:
    return "<int>[" + ", ".join(str(x) for x in b) + "]"


def main() -> int:
    if len(sys.argv) < 2:
        print("usage: gen_protected_defaults.py OUT.dart", file=sys.stderr)
        return 2
    out_path = sys.argv[1]

    raw = os.environ.get("DEFAULT_SUBS_JSON", "").strip()
    if not raw:
        print("::error::GitHub Secret «DEFAULT_SUBS_JSON» تنظیم نشده. "
              "Settings → Secrets and variables → Actions → New repository secret",
              file=sys.stderr)
        return 1

    try:
        items = json.loads(raw)
        assert isinstance(items, list) and items
        for it in items:
            assert it["id"] and it["name"] and it["url"].startswith(("http://", "https://"))
    except Exception:
        # عمداً محتوا را چاپ نمی‌کنیم تا لینک‌ها در لاگ نیایند.
        print("::error::DEFAULT_SUBS_JSON معتبر نیست. باید آرایهٔ JSON از "
              '{"id","name","url"} باشد.', file=sys.stderr)
        return 1

    master = os.urandom(32)
    shares = split_key(master)

    lines = [
        "// GENERATED by tools/gen_protected_defaults.py — do not edit, do not commit.",
        "// ignore_for_file: lines_longer_than_80_chars",
        "",
    ]
    for i, sh in enumerate(shares, 1):
        lines.append(f"const List<int> kPk{i} = {dart_bytes(sh)};")
    lines.append("")
    lines.append("/// [id, name, encryptedUrl(base64)]")
    lines.append("const List<List<String>> kProtectedEntries = <List<String>>[")
    for it in items:
        blob = base64.b64encode(encrypt(master, it["url"].encode("utf-8"))).decode()
        lines.append(f"  <String>[{dart_str(it['id'])}, {dart_str(it['name'])}, {dart_str(blob)}],")
    lines.append("];")
    lines.append("")

    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"protected defaults generated: {len(items)} entries")
    return 0


if __name__ == "__main__":
    sys.exit(main())
